package com.housekeeping.dao;

import com.housekeeping.bean.AccountCustomer;
import com.housekeeping.bean.AccountCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    long countByExample(AccountCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int deleteByExample(AccountCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int insert(AccountCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int insertSelective(AccountCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    List<AccountCustomer> selectByExample(AccountCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    AccountCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") AccountCustomer record, @Param("example") AccountCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByExample(@Param("record") AccountCustomer record, @Param("example") AccountCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByPrimaryKeySelective(AccountCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_customer
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByPrimaryKey(AccountCustomer record);
}