package com.housekeeping.dao;

import com.housekeeping.bean.AccountHousekeeper;
import com.housekeeping.bean.AccountHousekeeperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountHousekeeperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    long countByExample(AccountHousekeeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int deleteByExample(AccountHousekeeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int insert(AccountHousekeeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int insertSelective(AccountHousekeeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    List<AccountHousekeeper> selectByExample(AccountHousekeeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    AccountHousekeeper selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") AccountHousekeeper record, @Param("example") AccountHousekeeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByExample(@Param("record") AccountHousekeeper record, @Param("example") AccountHousekeeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByPrimaryKeySelective(AccountHousekeeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_housekeeper
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    int updateByPrimaryKey(AccountHousekeeper record);
}