package com.housekeeping.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.telephone
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.password
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.realname
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.status
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.user_face
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String userFace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.gender
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.register_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private Long registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.ast_login_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private Long astLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id_photo_positive
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String idPhotoPositive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id_photo_negative
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String idPhotoNegative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.bank_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.comment
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.score
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.balance
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private String balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.role_id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id
     *
     * @return the value of base_user.id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id
     *
     * @param id the value for base_user.id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.telephone
     *
     * @return the value of base_user.telephone
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.telephone
     *
     * @param telephone the value for base_user.telephone
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.password
     *
     * @return the value of base_user.password
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.password
     *
     * @param password the value for base_user.password
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.realname
     *
     * @return the value of base_user.realname
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.realname
     *
     * @param realname the value for base_user.realname
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.status
     *
     * @return the value of base_user.status
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.status
     *
     * @param status the value for base_user.status
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.user_face
     *
     * @return the value of base_user.user_face
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getUserFace() {
        return userFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.user_face
     *
     * @param userFace the value for base_user.user_face
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setUserFace(String userFace) {
        this.userFace = userFace == null ? null : userFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.gender
     *
     * @return the value of base_user.gender
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.gender
     *
     * @param gender the value for base_user.gender
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.register_time
     *
     * @return the value of base_user.register_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public Long getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.register_time
     *
     * @param registerTime the value for base_user.register_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.ast_login_time
     *
     * @return the value of base_user.ast_login_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public Long getAstLoginTime() {
        return astLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.ast_login_time
     *
     * @param astLoginTime the value for base_user.ast_login_time
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setAstLoginTime(Long astLoginTime) {
        this.astLoginTime = astLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id_card
     *
     * @return the value of base_user.id_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id_card
     *
     * @param idCard the value for base_user.id_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id_photo_positive
     *
     * @return the value of base_user.id_photo_positive
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getIdPhotoPositive() {
        return idPhotoPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id_photo_positive
     *
     * @param idPhotoPositive the value for base_user.id_photo_positive
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setIdPhotoPositive(String idPhotoPositive) {
        this.idPhotoPositive = idPhotoPositive == null ? null : idPhotoPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id_photo_negative
     *
     * @return the value of base_user.id_photo_negative
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getIdPhotoNegative() {
        return idPhotoNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id_photo_negative
     *
     * @param idPhotoNegative the value for base_user.id_photo_negative
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setIdPhotoNegative(String idPhotoNegative) {
        this.idPhotoNegative = idPhotoNegative == null ? null : idPhotoNegative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.bank_card
     *
     * @return the value of base_user.bank_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.bank_card
     *
     * @param bankCard the value for base_user.bank_card
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.comment
     *
     * @return the value of base_user.comment
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.comment
     *
     * @param comment the value for base_user.comment
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.score
     *
     * @return the value of base_user.score
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.score
     *
     * @param score the value for base_user.score
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.balance
     *
     * @return the value of base_user.balance
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.balance
     *
     * @param balance the value for base_user.balance
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.role_id
     *
     * @return the value of base_user.role_id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.role_id
     *
     * @param roleId the value for base_user.role_id
     *
     * @mbg.generated Fri Mar 05 10:54:27 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}